In [1]:
import os
import matplotlib.pyplot as plt
import numpy as np
import cv2
from skimage.io import imread
from skimage.transform import resize

In [2]:
# CATEGORIES = ['bougainvillea','garden_roses','gardenias','hibiscus','hydrangeas','lilies',
#               'orchids','peonies','sunflower','tulip']

target = []
images = []
flat_data = []

categories = []
datadir = 'D:\\Images\\flowers1'

for category in os.listdir(datadir):
    categories.append(category)

for category in categories:
    path = os.path.join(datadir,category)
    class_num = categories.index(category)

    for img in os.listdir(path):
        img_array = imread(os.path.join(path,img))
        #print(img_array.shape)
        img_resized = resize(img_array,(150,150,3))
        flat_data.append(img_resized.flatten())
        images.append(img_resized)
        target.append(class_num)

In [3]:
# print(flat_data)
print(categories)
print(images)


['bougainvillea', 'gardenias', 'garden_roses', 'hibiscus', 'hydrangeas']
[array([[[0.38094118, 0.06403399, 0.44497516],
        [0.44184314, 0.05909804, 0.52290196],
        [0.44236601, 0.03529412, 0.51487582],
        ...,
        [0.54495425, 0.32435294, 0.52780392],
        [0.53956863, 0.27880784, 0.53878431],
        [0.56494118, 0.2812366 , 0.57775163]],

       [[0.43298039, 0.09454641, 0.52317647],
        [0.41952941, 0.06246275, 0.50861961],
        [0.40070588, 0.0248366 , 0.46677124],
        ...,
        [0.48027451, 0.22091503, 0.46411765],
        [0.49526275, 0.2309098 , 0.48349804],
        [0.5131634 , 0.23591111, 0.51538824]],

       [[0.44518954, 0.10095425, 0.52836601],
        [0.41941176, 0.07294118, 0.50156863],
        [0.40928105, 0.04928105, 0.46947712],
        ...,
        [0.59117647, 0.29392157, 0.59732026],
        [0.61352941, 0.30098039, 0.60705882],
        [0.52764706, 0.22928105, 0.52577778]],

       ...,

       [[0.46840523, 0.40666667, 0.39284

In [4]:
flat_data = np.array(flat_data)
target = np.array(target)
images = np.array(images)

In [5]:
print(len(flat_data))
flat_data

359


array([[0.38094118, 0.06403399, 0.44497516, ..., 0.15109804, 0.13436601,
        0.15654379],
       [0.65294118, 0.3745098 , 0.58137255, ..., 0.49117647, 0.46960784,
        0.35686275],
       [0.03529412, 0.10749673, 0.00392157, ..., 0.0690915 , 0.17266667,
        0.01245752],
       ...,
       [0.56797386, 0.56851852, 0.3248366 , ..., 0.14912854, 0.23671024,
        0.29281046],
       [0.33764706, 0.43636601, 0.41215686, ..., 0.00327582, 0.12156863,
        0.02437124],
       [0.        , 0.        , 0.        , ..., 0.        , 0.0620915 ,
        0.02810458]])

In [6]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4,

In [7]:
print(len(images[4]))
# images

150


In [8]:
unique,count = np.unique(target,return_counts=True)
fig = plt.figure(figsize = (15, 5))
plt.bar(categories,count, color ='blue',width = 0.6)

<BarContainer object of 5 artists>

# Training our model¶

In [9]:
# Spliting data into train Test

from sklearn import metrics
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(flat_data,target,test_size=0.25, random_state=42)

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm

param_grid = [
  {'C': [1, 10, 100], 'kernel': ['linear']}
 ]

svc = svm.SVC(probability=True)
clf = GridSearchCV(svc, param_grid)
clf.fit(X_train, y_train)

GridSearchCV(estimator=SVC(probability=True),
             param_grid=[{'C': [1, 10, 100], 'kernel': ['linear']}])

In [12]:
ypred = clf.predict(X_test)

In [13]:
accuracy = clf.score(X_test,y_test) #Getting accuracy of our model Test
acuracy_train = clf.score(X_train,y_train) #Getting accuracy of our model Train
print(accuracy)

0.6777777777777778


In [14]:
cm = metrics.confusion_matrix(ypred, y_test)

print("Confussion Metrics : ","\n",cm)

Confussion Metrics :  
 [[16  0  1  2  0]
 [ 0 17  1  1  5]
 [ 4  1 11  1  2]
 [ 1  0  2  7  1]
 [ 0  3  2  2 10]]


In [15]:
import pickle

In [21]:
# with open('img_model1.pkl','wb') as file:
#     pickle.dump(clf,file)

In [22]:
model = pickle.load(open('img_model1.pkl','rb'))

In [23]:
# Testing A new Image
categories = ['bougainvillea','garden_roses','gardenias','hibiscus','hydrangeas']
flat_data = []
url = input('Enter image URL')
img = imread(url)
print(img)
img_resized = resize(img,(150,150,3))
flat_data.append(img_resized.flatten())
flat_data = np.array(flat_data)
print(img.shape)
plt.imshow(img_resized)

output = model.predict(flat_data)
output1 = categories[output[0]]
print(f'PREDICTED OUTPUT : {output1}')
q = model.predict_proba(flat_data)
for index, item in enumerate(categories):
    print(f'{item} : {q[0][index]*100}%')


Enter image URLhttps://image.freepik.com/free-photo/pink-purple-flowers_1203-2191.jpg
[[[206 202 219]
  [210 206 223]
  [211 207 224]
  ...
  [207 190 226]
  [229 148 225]
  [218 135 213]]

 [[211 207 222]
  [210 206 221]
  [212 208 223]
  ...
  [207 163 214]
  [244 141 232]
  [235 130 222]]

 [[225 219 233]
  [215 209 223]
  [212 206 220]
  ...
  [235 153 225]
  [255 127 236]
  [239 106 215]]

 ...

 [[231 171 231]
  [232 172 232]
  [233 174 232]
  ...
  [241 123 199]
  [255 107 208]
  [249  97 197]]

 [[241 177 238]
  [234 175 233]
  [229 176 230]
  ...
  [223 115 190]
  [249  92 195]
  [244  94 193]]

 [[231 188 233]
  [227 184 230]
  [230 184 231]
  ...
  [245  83 194]
  [240  85 189]
  [241  86 190]]]
(417, 626, 3)
PREDICTED OUTPUT : bougainvillea
bougainvillea : 62.626201031163276%
garden_roses : 2.256211099798249%
gardenias : 15.618757230372118%
hibiscus : 1.202237233062915%
hydrangeas : 18.2965934056034%


In [ ]:
model.predict_proba(flat_data)