In [1]:
import os
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
from skimage.transform import resize

In [2]:
target = []
images = []
# flat_data = []

categories = []
datadir = 'D:\\Images\\dog_cat'

for category in os.listdir(datadir):
    categories.append(category)

for category in categories:
    path = os.path.join(datadir,category)
    class_num = categories.index(category)

    for img in os.listdir(path):
        img_array = imread(os.path.join(path,img))
        #print(img_array.shape)
        img_resized = resize(img_array,(150,150,3))
#         flat_data.append(img_resized.flatten())
        images.append(img_resized)
        target.append(class_num)

In [3]:
# print(flat_data)
# print(categories)
# print(images)
type(target)

list

In [4]:
# flat_data = np.array(flat_data)
target = np.array(target)
images = np.array(images)

In [5]:
# print(flat_data.shape)
print(categories)
print(images.shape)
type(target.shape)

['cats', 'dogs']
(3074, 150, 150, 3)


tuple

In [6]:
from sklearn import metrics
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(images,target,test_size=0.2, random_state=242)

In [7]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
print(y_train[:10])

(2459, 150, 150, 3)
(2459,)
(615, 150, 150, 3)
(615,)
[1 0 0 1 0 1 0 0 0 1]


In [13]:
import numpy as np
import tensorflow as tf
from tensorflow.python.keras.utils.data_utils import Sequence
import autokeras as ak
tf.keras.backend.set_floatx('float64')

In [14]:
# Initialize the image classifier.

clf = ak.ImageClassifier(
    overwrite=True,
    max_trials=1)
# Feed the image classifier with training data.
history = clf.fit(x_train, y_train, epochs=10)

Trial 1 Complete [00h 35m 29s]
val_loss: 0.6186585219282853

Best val_loss So Far: 0.6186585219282853
Total elapsed time: 00h 35m 29s
INFO:tensorflow:Oracle triggered exit
Epoch 1/10
77/77 [==============================] - 240s 3s/step - loss: 0.8043 - accuracy: 0.5421
Epoch 2/10
77/77 [==============================] - 236s 3s/step - loss: 0.6138 - accuracy: 0.6373
Epoch 3/10
77/77 [==============================] - 222s 3s/step - loss: 0.5031 - accuracy: 0.7617
Epoch 4/10
77/77 [==============================] - 236s 3s/step - loss: 0.3595 - accuracy: 0.8438
Epoch 5/10
77/77 [==============================] - 228s 3s/step - loss: 0.2564 - accuracy: 0.9028
Epoch 6/10
77/77 [==============================] - 290s 4s/step - loss: 0.1784 - accuracy: 0.9280
Epoch 7/10
77/77 [==============================] - 296s 4s/step - loss: 0.1377 - accuracy: 0.9553
Epoch 8/10
77/77 [==============================] - 285s 4s/step - loss: 0.1176 - accuracy: 0.9610
Epoch 9/10
77/77 [==================

In [26]:
pred_y = clf.predict(x_test)
pred_y

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],

In [30]:
from sklearn.metrics import classification, accuracy_score,classification_report, confusion_matrix

C:\Users\satyam.singh\anaconda3\envs\keras\lib\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.metrics.classification module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)


In [32]:
cm = confusion_matrix(y_test,pred_y)
cm

array([[154, 141],
       [ 72, 248]], dtype=int64)

In [34]:
accuracy_score(y_test,pred_y)

0.6536585365853659

In [36]:
print(classification_report(y_test,pred_y))

              precision    recall  f1-score   support

           0       0.68      0.52      0.59       295
           1       0.64      0.78      0.70       320

    accuracy                           0.65       615
   macro avg       0.66      0.65      0.65       615
weighted avg       0.66      0.65      0.65       615



In [50]:
print(len(pred_y))

615


In [53]:
print('Accuracy: {accuracy}'.format(accuracy=clf.evaluate(x_test, y_test)))

20/20 [==============================] - 10s 485ms/step - loss: 1.2247 - accuracy: 0.6537
Accuracy: [1.2247061913575583, 0.6536585365853659]


In [94]:
clf.export_autokeras_model('my_autokeras_model.h5')

AttributeError: 'ImageClassifier' object has no attribute 'export_autokeras_model'

In [90]:
import pickle
with open("mode"+".pickle", 'wb') as file:
            pickle.dump(clf, file)

AttributeError: Can't pickle local object 'AddOneDimension.__init__.<locals>.<lambda>'

In [58]:
# Export Model
model = clf.export_model()
print(type(model))  # <class 'tensorflow.python.keras.engine.training.Model'>

<class 'tensorflow.python.keras.engine.functional.Functional'>


In [59]:
# Saving Model
try:
    model.save("dog_cat_autokeras", save_format="tf")
except:
    model.save("dog_cat_autokeras.h5")


INFO:tensorflow:Assets written to: dog_cat_autokeras\assets


In [67]:
# Loading model
from tensorflow.keras.models import load_model

model = load_model("dog_cat_autokeras", custom_objects=ak.CUSTOM_OBJECTS)

model

In [72]:
# Predicting with classifier
clf.predict(x_train)

array([[1.],
       [0.],
       [0.],
       ...,
       [0.],
       [1.],
       [0.]])

In [73]:
# Model Summary
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 150, 150, 3)]     0         
_________________________________________________________________
cast_to_float32 (CastToFloat (None, 150, 150, 3)       0         
_________________________________________________________________
normalization (Normalization (None, 150, 150, 3)       7         
_________________________________________________________________
conv2d (Conv2D)              (None, 148, 148, 32)      896       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 146, 146, 64)      18496     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 73, 73, 64)        0         
_________________________________________________________________
dropout (Dropout)            (None, 73, 73, 64)       

In [76]:
# Training and testing datatype
print(x_train.dtype)
print(x_test.dtype)
print(y_train.dtype)

float64
float64
int32


In [79]:
res = model.predict(x_test)

In [80]:
type(res)

numpy.ndarray

In [110]:
# Export model in pickle autokeras
clf.export_model().save("dog_cat.h5", save_format="h5")


In [112]:
from tensorflow.keras.models import load_model

loaded_model = load_model("dog_cat.h5", custom_objects=ak.CUSTOM_OBJECTS)

predicted_y = loaded_model.predict(x_test)
print(predicted_y)

[[1.67843085e-01]
 [6.32269092e-01]
 [9.81963417e-02]
 [7.30837888e-01]
 [1.00000000e+00]
 [5.19692999e-01]
 [9.67946514e-01]
 [9.99255151e-01]
 [9.83030745e-01]
 [4.29440684e-02]
 [9.37616229e-01]
 [9.20946754e-01]
 [9.86123294e-01]
 [9.90798958e-01]
 [1.00000000e+00]
 [9.95730782e-01]
 [9.99996642e-01]
 [9.96081209e-01]
 [9.99932997e-01]
 [8.79201732e-01]
 [6.40942303e-01]
 [4.18573503e-01]
 [1.32429492e-03]
 [8.06436554e-01]
 [9.92115713e-01]
 [2.70192804e-01]
 [5.44414812e-03]
 [3.88885824e-02]
 [8.20663658e-01]
 [9.90041560e-01]
 [9.99947721e-01]
 [9.97781489e-01]
 [5.15885384e-02]
 [8.99442137e-01]
 [9.88391770e-01]
 [1.83771566e-05]
 [9.92948171e-01]
 [7.53407760e-01]
 [9.50452639e-01]
 [9.89824772e-01]
 [9.99882661e-01]
 [1.62791622e-01]
 [1.48457266e-01]
 [9.92750457e-01]
 [7.15162762e-03]
 [1.47143837e-01]
 [2.98628132e-03]
 [2.43613933e-01]
 [9.99975526e-01]
 [9.80395654e-01]
 [2.26240436e-02]
 [2.52985196e-01]
 [7.26279055e-01]
 [9.99434131e-01]
 [9.99873037e-01]
 [3.078489